### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by AethLi** [Dhruvkumarshah/maven-dependency-explorer#2]
I've read source code for this extension.There's some question:

1. Command "maven-dependency-explorer.exploer" export dependency:tree to a temp file, this file is a global file, it will case some problem to multi-project(with multi-window) user (just in my guess, but I've never bring out this error). This temp file may cache into .vscode/ or somewhere else.

2. Will you give a view to display jars from maven dependency just like what IDEA done?
![image](https://user-images.githubusercontent.com/25505798/122662879-06f0ad00-d1c9-11eb-996b-35915b318b9c.png)

**Comment by Dhruvkumarshah** [comment]
Hello @AethLi ,
1) This plugin won't work for the multi-maven project, I yet to add functionally. The temp-file will be deleted on destroyed.
2) VsCode maven plugin already does that, so not adding that to this plugin will make any impact.

**Comment by tzolov** [comment]
Just for information, 
Most of the projects i'm working on are multi-maven projects. So until the multi-maven support is provided the extension wont work for me
